# Generated by Django 5.0.6 on 2024-06-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_user_userr_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
