# Generated by Django 5.0.6 on 2024-07-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='document',
            field=models.FileField(default=0, upload_to='documents/'),
        ),
    ]
